### ISSUE TITLE
Type error in the importstrategy helper

### ISSUE THREAD

**Issue by mrfroasty** [oroinc/OroAkeneoBundle#55]
When running other integrations, the helper which decorate core helper causes failure.

`  [TypeError]
  Argument 1 passed to Symfony\Component\Validator\Mapping\GenericMetadata::addConstraint() must be an instance of Symfony\Component\Validator\Constraint, instance of Oro\Bundle\ImportExportBundle\Context\StepExecutionProxyCont
  ext given, called in /app/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/GenericMetadata.php on line 184

Exception trace:
  at /app/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/GenericMetadata.php:140
 Symfony\Component\Validator\Mapping\GenericMetadata->addConstraint() at /app/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/GenericMetadata.php:184
 Symfony\Component\Validator\Mapping\GenericMetadata->addConstraints() at /app/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php:106
 Symfony\Component\Validator\Validator\RecursiveContextualValidator->validate() at /app/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveValidator.php:93
 Symfony\Component\Validator\Validator\RecursiveValidator->validate() at /app/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/TraceableValidator.php:66
 Symfony\Component\Validator\Validator\TraceableValidator->validate() at /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Strategy/Import/ImportStrategyHelper.php:308
 Oro\Bundle\ImportExportBundle\Strategy\Import\ImportStrategyHelper->validateEntity() at /app/vendor/oro/commerce-akeneo/ImportExport/Strategy/ImportStrategyHelper.php:125
 Oro\Bundle\AkeneoBundle\ImportExport\Strategy\ImportStrategyHelper->addValidationErrors() at /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Strategy/Import/ConfigurableAddOrReplaceStrategy.php:416
 Oro\Bundle\ImportExportBundle\Strategy\Import\ConfigurableAddOrReplaceStrategy->processValidationErrors() at /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Strategy/Import/ConfigurableAddOrReplaceStrategy.php:399
 Oro\Bundle\ImportExportBundle\Strategy\Import\ConfigurableAddOrReplaceStrategy->validateAndUpdateContext() at /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Strategy/Import/ConfigurableAddOrReplaceStrategy.php:117
 Oro\Bundle\ImportExportBundle\Strategy\Import\ConfigurableAddOrReplaceStrategy->process() at /app/src/Madia/Bundle/NavisionBundle/ImportExport/Strategy/CustomerAddressStrategy.php:21
 Madia\Bundle\NavisionBundle\ImportExport\Strategy\CustomerAddressStrategy->process() at /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Processor/ImportProcessor.php:100
 Oro\Bundle\ImportExportBundle\Processor\ImportProcessor->process() at /app/vendor/oro/platform/src/Oro/Bundle/BatchBundle/Step/StepExecutor.php:191
 Oro\Bundle\BatchBundle\Step\StepExecutor->process() at /app/vendor/oro/platform/src/Oro/Bundle/BatchBundle/Step/StepExecutor.php:160
 Oro\Bundle\BatchBundle\Step\StepExecutor->execute() at /app/vendor/oro/platform/src/Oro/Bundle/BatchBundle/Step/ItemStep.php:33
 Oro\Bundle\BatchBundle\Step\ItemStep->doExecute() at /app/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Step/AbstractStep.php:162
 Akeneo\Bundle\BatchBundle\Step\AbstractStep->execute() at /app/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Job/Job.php:401
 Akeneo\Bundle\BatchBundle\Job\Job->handleStep() at /app/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Job/Job.php:361
 Akeneo\Bundle\BatchBundle\Job\Job->doExecute() at /app/vendor/akeneo/batch-bundle/Akeneo/Bundle/BatchBundle/Job/Job.php:296
 Akeneo\Bundle\BatchBundle\Job\Job->execute() at /app/vendor/oro/platform/src/Oro/Bundle/IntegrationBundle/ImportExport/Job/Executor.php:30
 Oro\Bundle\IntegrationBundle\ImportExport\Job\Executor->doJob() at /app/vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Job/JobExecutor.php:110
 Oro\Bundle\ImportExportBundle\Job\JobExecutor->executeJob() at /app/var/cache/dev/ContainerTRako5k/Executor_618db2e.php:36
 Executor_618db2e->executeJob() at /app/vendor/oro/platform/src/Oro/Bundle/IntegrationBundle/Provider/SyncProcessor.php:268
 Oro\Bundle\IntegrationBundle\Provider\SyncProcessor->processImport() at /app/vendor/oro/platform/src/Oro/Bundle/IntegrationBundle/Provider/SyncProcessor.php:251
 Oro\Bundle\IntegrationBundle\Provider\SyncProcessor->processIntegrationConnector() at /app/vendor/oro/platform/src/Oro/Bundle/IntegrationBundle/Provider/SyncProcessor.php:98
 Oro\Bundle\IntegrationBundle\Provider\SyncProcessor->processConnectors() at /app/vendor/oro/platform/src/Oro/Bundle/IntegrationBundle/Provider/SyncProcessor.php:73
 Oro\Bundle\IntegrationBundle\Provider\SyncProcessor->process() at /app/var/cache/dev/ContainerTRako5k/SyncProcessor_85b423b.php:31
 SyncProcessor_85b423b->process() at /app/src/Madia/Bundle/NavisionBundle/Async/CustomerSyncIntegrationProcessor.php:103
 Madia\Bundle\NavisionBundle\Async\CustomerSyncIntegrationProcessor->Madia\Bundle\NavisionBundle\Async\{closure}() at n/a:n/a
 call_user_func() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Job/JobRunner.php:207
 Oro\Component\MessageQueue\Job\JobRunner->callbackResult() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Job/JobRunner.php:152
 Oro\Component\MessageQueue\Job\JobRunner->runDelayed() at /app/src/Madia/Bundle/NavisionBundle/Async/CustomerSyncIntegrationProcessor.php:107
 Madia\Bundle\NavisionBundle\Async\CustomerSyncIntegrationProcessor->process() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Client/DelegateMessageProcessor.php:36
 Oro\Component\MessageQueue\Client\DelegateMessageProcessor->process() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Consumption/QueueConsumer.php:192
 Oro\Component\MessageQueue\Consumption\QueueConsumer->doConsume() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Consumption/QueueConsumer.php:127
 Oro\Component\MessageQueue\Consumption\QueueConsumer->consume() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Client/ConsumeMessagesCommand.php:101
 Oro\Component\MessageQueue\Client\ConsumeMessagesCommand->consume() at /app/vendor/oro/platform/src/Oro/Bundle/MessageQueueBundle/Command/ClientConsumeMessagesCommand.php:58
 Oro\Bundle\MessageQueueBundle\Command\ClientConsumeMessagesCommand->consume() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Client/ConsumeMessagesCommand.php:91
 Oro\Component\MessageQueue\Client\ConsumeMessagesCommand->execute() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1018
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:271
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:147
 Symfony\Component\Console\Application->run() at /app/bin/console:33`

**Comment by mrfroasty** [comment]
I have also added pull request with the related fix.

**Comment by dxops** [comment]
https://github.com/oroinc/OroAkeneoBundle/releases/tag/4.1.14
https://github.com/oroinc/OroAkeneoBundle/releases/tag/3.1.23

Fixed, thank you @mrfroasty !
