### ISSUE TITLE
Error after upgrade to new version

### ISSUE THREAD

**Issue by yaroslavbr** [oroinc/OroAkeneoBundle#58]
https://github.com/oroinc/OroAkeneoBundle/blob/8981987f4f1c6e6cd22ac96da9cf951b36c04933/ImportExport/Strategy/ImportStrategyHelper.php#L96

I updated commerce-enterprise to version 4.1.14, composer updated all dependencies as well. Now I getting such error:
`PHP Fatal error: Access level to Oro\Bundle\AkeneoBundle\ImportExport\Strategy\ImportStrategyHelper::getEntityPropertiesByClassName() must be protected (as in class Oro\Bundle\ImportExportBundle\Strategy\Import\ImportStrategyHelper) or weaker in /app/vendor/oro/commerce-akeneo/ImportExport/Strategy/ImportStrategyHelper.php on line 148`

**Comment by dxops** [comment]
Fixed https://github.com/oroinc/OroAkeneoBundle/commit/f89675a099f166c88e9102c502bc3b53d12c5a1e
Thank you @yaroslavbr
