### ISSUE TITLE
Attempted to call an undefined method named "setEnabled" of class "Oro\Bundle\AkeneoBundle\EventListener\DoctrineTagEventListenerDecorator"

### ISSUE THREAD

**Issue by yaroslavbr** [oroinc/OroAkeneoBundle#59]
After upgradee to oro/commerce-enterprise  4.1.14 and updating all dependencies with `composer update` I getting error while running consumer:

`2021-06-24 17:21:45 doctrine.DEBUG: SELECT * FROM oro_message_queue WHERE consumer_id=:consumerId AND queue=:queue LIMIT 1 ["consumerId" => "60d4a309a36c48.63275393","queue" => "oro.default"] ["memory_usage" => "111.85 MB"]

In OptionalListenerManager.php line 88:
                                                                                                                                                
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                                                  
  Attempted to call an undefined method named "setEnabled" of class "Oro\Bundle\AkeneoBundle\EventListener\DoctrineTagEventListenerDecorator".  
                                                                                                                                                

Exception trace:
  at /app/vendor/oro/platform/src/Oro/Bundle/PlatformBundle/Manager/OptionalListenerManager.php:88
 Oro\Bundle\PlatformBundle\Manager\OptionalListenerManager->enableListener() at /app/vendor/oro/platform/src/Oro/Bundle/PlatformBundle/Manager/OptionalListenerManager.php:106
 Oro\Bundle\PlatformBundle\Manager\OptionalListenerManager->enableListeners() at /app/vendor/oro/platform/src/Oro/Bundle/MessageQueueBundle/Platform/OptionalListenerExtension.php:26
 Oro\Bundle\MessageQueueBundle\Platform\OptionalListenerExtension->onPreReceived() at /app/vendor/oro/platform/src/Oro/Bundle/MessageQueueBundle/Consumption/Extension/ChainExtension.php:62
 Oro\Bundle\MessageQueueBundle\Consumption\Extension\ChainExtension->onPreReceived() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Consumption/ChainExtension.php:44
 Oro\Component\MessageQueue\Consumption\ChainExtension->onPreReceived() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Consumption/QueueConsumer.php:182
 Oro\Component\MessageQueue\Consumption\QueueConsumer->doConsume() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Consumption/QueueConsumer.php:127
 Oro\Component\MessageQueue\Consumption\QueueConsumer->consume() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Client/ConsumeMessagesCommand.php:101
 Oro\Component\MessageQueue\Client\ConsumeMessagesCommand->consume() at /app/vendor/oro/platform/src/Oro/Bundle/MessageQueueBundle/Command/ClientConsumeMessagesCommand.php:58
 Oro\Bundle\MessageQueueBundle\Command\ClientConsumeMessagesCommand->consume() at /app/vendor/oro/platform/src/Oro/Component/MessageQueue/Client/ConsumeMessagesCommand.php:91
 Oro\Component\MessageQueue\Client\ConsumeMessagesCommand->execute() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:149
 Symfony\Component\Console\Application->run() at /app/bin/console:33
`

 composer info | grep oro/:

`oro/calendar-bundle                              4.1.12             Calendar bundle for OroPlatform-based applications.
oro/commerce                                     4.1.14             OroCommerce - an open-source Business to Business Commerce application. \nThis package contains bundles and needs to be added as a dependency in an OroCommerce application.
oro/commerce-akeneo                              4.1.23             Akeneo PIM OroCommerce Connector.
oro/commerce-crm                                 4.1.9              OroCRM integration for OroCommerce
oro/commerce-crm-ee                              4.1.12             OroCommerce OroCRM Enterprise Bridge
oro/commerce-enterprise                          4.1.14             OroCommerce Enterprise.
oro/crm                                          4.1.14             OroCRM
oro/crm-call-bundle                              4.1.9              Oro Call Bundle
oro/crm-dotmailer                                4.1.8              Oro Dotmailer integration
oro/crm-enterprise                               4.1.6              OroCRM Enterprise
oro/crm-hangouts-call-bundle                     4.1.1              Oro Google Hangouts integration
oro/crm-magento-embedded-contact-us              4.1.2              OroCRM Magento Embedded Contact Us package
oro/crm-pro-ldap-bundle                          4.1.5              OroCRM Pro LDAP Bundle
oro/crm-task-bundle                              4.1.7              Oro Task Bundle
oro/crm-zendesk                                  4.1.5              OroCRM Zendesk Integration
oro/customer-portal                              4.1.14            
oro/doctrine-extensions                          1.2.2              Doctrine Extensions for MySQL and PostgreSQL.
oro/google-tag-manager-bundle                    4.1.7              Oro Google Tag Manager integration
oro/gridfs-config                                4.1.0              GridFS adapter configuration for Gaufrette
oro/health-check-bundle                          4.1.2              Oro Health Check Bundle
oro/marketing                                    4.1.10             Oro Marketing Bundles
oro/multi-host                                   4.1.6              Oro Multi-Host deployment support for BAP
oro/oauth2-server                                4.1.11             Oro OAuth 2.0 authorization and resource server for BAP
oro/platform                                     4.1.14             Business Application Platform (BAP)
oro/platform-enterprise                          4.1.14             OroPlatform Enterprise
oro/platform-serialised-fields                   4.1.7              OroPlatform Serialized Fields
oro/redis-config                                 4.1.5              OroRedisConfigBundle
oro/twig-inspector                               1.0.3              Oro Twig Inspector adds the possibility to find twig templates and blocks used for rendering HTML pages faster during development
`

**Comment by dxops** [comment]
Fixed https://github.com/oroinc/OroAkeneoBundle/commit/f89675a099f166c88e9102c502bc3b53d12c5a1e
Thank you @yaroslavbr
