### ISSUE TITLE
Attribute options sorting order lost after sync (AttributeConnector)

### ISSUE THREAD

**Issue by yaroslavbr** [oroinc/OroAkeneoBundle#60]
**STR**

- sort options fro certain attribute from Akeneo

![BEFORE-SYNC](https://user-images.githubusercontent.com/5465204/132006644-c6f90c67-8190-4dac-950f-c5a69af9d760.png)

- schedule and run Akeneo integration sync with AttributeConnector enabled
 **Actual:**  Attribute options sorting lost:
![AFTER-SYNC](https://user-images.githubusercontent.com/5465204/132006808-a65ae966-488b-4d7f-b66f-01a94cabc95e.png)

**Expected:** sorting should not be lost for existing options

**Comment by dxops** [comment]
@yaroslavbr check sort_order from Akeneo side please 
https://github.com/oroinc/OroAkeneoBundle/blob/4.2/Integration/Iterator/AttributeIterator.php#L111
