### ISSUE TITLE
import Issue after enabled this bundle 

### ISSUE THREAD

**Issue by hamdallah90** [oroinc/OroAkeneoBundle#68]
Hello,

after we enabled this bundle we have founded an issue with all import functionality with this error

The identifier id is missing for a query of Oro\Bundle\IntegrationBundle\Entity\Channel

Cheers

**Comment by dxops** [comment]
Hello, fixed in https://github.com/oroinc/OroAkeneoBundle/releases/tag/5.0.0-beta4, thank you
