### ISSUE TITLE
Configurable Product import issue

### ISSUE THREAD

**Issue by rtaschetto** [oroinc/OroAkeneoBundle#70]
``Using the latest version "5.0.0-beta5" and Akeneo 5  we have the following problem. 

Let's explain the case:
On Akeneo there is a model "A" (first level configurable product), under which there is a model "B" (second level configurable product) and finally the variant products "C", "D", "E". 
After importing the configurable products and products, the situation in OroCommerce is as follows:
- configurable product "B" has "C","D","E" simple product variants (correct)
- configurable product "A" has no  simple product variant (wrong)

Regardless of the value chosen in parameter "Image Attribute Filter" ( "Enable 1st and 2nd level configurable products" or "Enable 1st level configurable products") configurable product "A" never have product variants.

analyzing the code, we found a couple of errors (or at least to us they seem errors).

```php
vendor/oro/commerce-akeneo/ImportExport/Writer/ConfigurableAsyncWriter.php:64

   public function write(array $items)
    {
        foreach ($items as $item) {
            $sku = $item['sku'];

            if (!empty($item['family_variant'])) {
                if (isset($item['parent'], $this->variants[$sku])) {
                    $parent = $item['parent'];
                    foreach (array_keys($this->variants[$sku]) as $sku) {
                        $this->variants[$parent][$sku] = ['parent' => $parent, 'variant' => $sku];
                    }
                }

                return;
            }

            if (empty($item['parent'])) {
                return;
            }

            $parent = $item['parent'];

            $this->variants[$parent][$sku] = ['parent' => $parent, 'variant' => $sku];
        }
    }
```

return instruction at lines 77,81 must be a "continue" instruction (probably a cut&paste error from old  AsyncProcessor : vendor/oro/commerce-akeneo/ImportExport/Processor/AsyncProcessor.php:21). 

```
vendor/oro/commerce-akeneo/Integration/AkeneoTransport.php:241

    public function getProductsList(int $pageSize): iterable
    {
        $this->initAttributesList();

        $queryParams = [
            'scope' => $this->transportEntity->getAkeneoActiveChannel(),
            'search' => $this->akeneoSearchBuilder->getFilters($this->transportEntity->getProductFilter()),
            'attributes' => key($this->attributes),
        ];

        if ($this->transportEntity->getSyncProducts() === SyncProductsDataProvider::PUBLISHED) {
            return new ConfigurableProductIterator(
                $this->client->getPublishedProductApi()->all($pageSize, $queryParams),
                $this->client,
                $this->logger,
                $this->getAttributeMapping()
            );
        }

        return new ConfigurableProductIterator(
            $this->client->getProductApi()->all($pageSize, $queryParams),
            $this->client,
            $this->logger,
            $this->getAttributeMapping()
        );
    }

```

"return new ConfigurableProductIterator" at lines 252,260 must be "return new ProductIterator("

After changing this parts of code it seems to work.

Can you check please? Thank you.

**Comment by dxops** [comment]
Hello @rtaschetto , thank you for this report, I will check it as soon as possible.

**Comment by dxops** [comment]
@rtaschetto check https://github.com/oroinc/OroAkeneoBundle/releases/tag/5.0.0-rc2 please 

1) fixed, thank you
2) ProductIterator and ConfigurableProductIterator are similar, ConfigurableProductIterator is way smaller and contains values required to build the tree of configurable-to-single product relation and do not update products and models values.

So, we import products and models using ProductConnector

```
        $iterator = new \AppendIterator();
        $iterator->append($this->transport->getProducts(self::PAGE_SIZE));
        $iterator->append($this->transport->getProductModels(self::PAGE_SIZE));
```

with `return new ProductIterator` inside to import all products and models values.

In ConfigurableProductConnector we import list of products and models to build the tree using

```
        $iterator = new \AppendIterator();
        $iterator->append($this->transport->getProductsList(self::PAGE_SIZE));
        $iterator->append($this->transport->getProductModelsList(self::PAGE_SIZE));
```

with `return new ConfigurableProductIterator` inside to build the tree.

_Regardless of the value chosen in parameter "Image Attribute Filter" ( "Enable 1st and 2nd level configurable products" or "Enable 1st level configurable products") configurable product "A" never have product variants._

Multilevel Products config do not prevent product's import, but manages imported products status. If product wasn't imported try to check SKU in integration statuses to get validation results, like

```
Error found: File validation failed for element 1 of field Illustration: An empty file is not allowed.
```

Fix for the 1) item fixes the issue you've described, let me check if it works for you, please

**Comment by dxops** [comment]
https://github.com/oroinc/OroAkeneoBundle/releases/tag/4.1.38
https://github.com/oroinc/OroAkeneoBundle/releases/tag/4.2.16
https://github.com/oroinc/OroAkeneoBundle/releases/tag/5.0.1}

Fixed more issues, thank you
