### ISSUE TITLE
Products being enabled automatically

### ISSUE THREAD

**Issue by gplanchat** [oroinc/OroAkeneoBundle#72]
After discussion here: https://github.com/oroinc/OroAkeneoBundle/commit/d63935698ce0c0d934cf358b90a4a27c382d2d10#r75593668

We are suspecting there is one side effects on the activation of products since version 4.1.15 and the split of the product connector into a new product connector and the product model connector.

* [ ] Products that are disabled on the Akeneo side does not remain disabled on the Oro side, they are activated no matter which state they have on Akeneo.
* [ ] Manually disabled product models on Oro are re-activated by the connector if they have at least one variant.

This has consequences in 2 scenario we identified:
* Scenario 1
   * when activation/deactivation is made on the Akeneo side
   * and when the product filtering does import both enabled and disabled products
   * then the products are activated which ever state they have on Akeneo
* Scenario 2
   * when activation/deactivation is made on the Oro side
   * and when the product filtering does import only enabled products
   * then some manually deactivated products on Oro can be reactivated without warning

This is a sensible change in a minor version pushed on production. We would like to have control over this feature by disabling it.

**Comment by dxops** [comment]
This logic was working prior to 4.1.15 also https://github.com/oroinc/OroAkeneoBundle/blob/4.1.14/ImportExport/Processor/ProductVariantProcessor.php

**Comment by dxops** [comment]
Hey @gplanchat 

Fixed, thank you
https://github.com/oroinc/OroAkeneoBundle/releases/tag/4.1.38
https://github.com/oroinc/OroAkeneoBundle/releases/tag/4.2.16
https://github.com/oroinc/OroAkeneoBundle/releases/tag/5.0.1
