### ISSUE TITLE
Configurable product does not import

### ISSUE THREAD

**Issue by stijnkuppens** [oroinc/OroAkeneoBundle#73]
Hello,

I'm having problems with syncing configurable products. I have setup the Akeneo integration and everything imports well, except for the configurable products. 

Currently I have setup a product filter so not all products are imported every time.
Configurable product filter:
{"identifier":[{"operator":"=","value":"LAM_LVZ42"}]}

After scheduling I get the error message in the logs:
Error found: Product "LAM_LVZ42" not found.; Akeneo record: {"configurable":"LAM_LVZ42","variants":["CIB_44376"]}

The simple product is imported, but not the configurable one. The product has 4 variants in Akeneo and all data is there.

Do you have an idea what is going wrong here?

**Comment by dxops** [comment]
hello @stijnkuppens 

Update to the latest versions please
https://github.com/oroinc/OroAkeneoBundle/releases/tag/4.1.38
https://github.com/oroinc/OroAkeneoBundle/releases/tag/4.2.16
https://github.com/oroinc/OroAkeneoBundle/releases/tag/5.0.1
