### ISSUE TITLE
Import float attributes didn't update on product edit page

### ISSUE THREAD

**Issue by hamdallah90** [oroinc/OroAkeneoBundle#77]
Hello,

I have run import attributes, and all is ok, but all float "serialized fields" are not saved when trying to update the product. 

I have created a float field manual and it worked, but the problem exists only with the Akeneo field.

Thanks

**Comment by dxops** [comment]
Hello @hamdallah90 

Check this fix please https://github.com/oroinc/OroAkeneoBundle/commit/29e75c5a6055785dbd6cf8352b82098783583a8b
